# Generated by Django 4.2.3 on 2023-08-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.IntegerField(blank=True, null=True, verbose_name='ключ'),
        ),
    ]
