# Generated by Django 4.2.3 on 2023-07-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_blog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
